config/routes.rb
Rails.application.routes.draw do
  root to: 'boats#index'

  devise_for :users, path: "/", only: [:registrations, :sessions]
  resources :boats do
    resources :goods
  end
end

app/models/boat.rb
class Boat < ActiveRecord::Base
  has_attached_file :image, url: :set_image_url

  belongs_to :user
  has_many :goods, dependent: :destroy

  validates :name, :year, :user, :image, presence: true
  validates :year, numericality: { only_integer: true ,
    greater_than_or_equal_to: 0 }
  validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }

  def owner_by?(user)
    self.user == user
  end

  private
  def set_image_url
    "/images/users/#{self.user_id}/boat/:basename-#{self.id}.:extension"
  end
end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :boat

  validates :name, :quantity, :boat, presence: true
  validates :quantity, numericality: { only_integer: true,
    greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound do
    flash[:errors] = [I18n.t("errors.messages.record_not_found")]
    redirect_to root_path
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :load_instance, only: [:show, :edit, :update, :destroy]
  before_action :create_instance, only: [:new, :create]
  before_action :set_params, only: [:create, :update]
  before_action :check_authorization, only: [:show, :edit, :update, :destroy]

  def index
    @boats = current_user.boats.page(params[:page]).per(Settings.per_page.boat)
  end

  def show
    @goods = @boat.goods
  end

  def create
    if @boat.save
      flash[:success] = I18n.t("boats.create.success")
      redirect_to boats_path
    else
      flash[:errors] = @boat.errors.full_messages
      redirect_to boats_path
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @boat.save
      flash[:success] = I18n.t("boats.update.success")
      redirect_to boats_path
    else
      flash[:errors] = @boat.errors.full_messages
      redirect_to boats_path
    end
  end

  def destroy
    if @boat.destroy
      flash[:success] = I18n.t("boats.destroy.success")
      redirect_to root_path
    else
      flash[:errors] = @boat.errors.full_messages
      redirect_to boats_path
    end
  end

  private
  def load_instance
    @boat = Boat.find(params[:id])
  end

  def create_instance
    @boat = current_user.boats.new
  end

  def boat_params
    params.require(:boat).permit(:name, :year, :image) if params[:boat]
  end

  def set_params
    @boat.assign_attributes(boat_params)
  end

  def check_authorization
    unless @boat.owner_by?(current_user)
      flash[:errors] = [I18n.t("errors.messages.permission_invalid")]
      redirect_to root_path
    end
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :load_boat
  before_action :load_instance, only: [:edit, :update, :destroy]
  before_action :create_instance, only: [:new, :create]
  before_action :set_params, only: [:create, :update]

  def create
    if @good.save
      flash[:success] = I18n.t("boats.create.success")
      redirect_to boat_path(@boat)
    else
      flash[:errors] = @good.errors.full_messages
      render :new
    end
  end

  def new
  end

  def edit
  end

  def update
    if @good.save
      flash[:success] = I18n.t("goods.update.success")
      redirect_to boat_path(@boat)
    else
      flash[:errors] = @good.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @good.destroy
      flash[:success] = I18n.t("goods.destroy.success")
      redirect_to boat_path(@boat)
    else
      flash[:errors] = @good.errors.full_messages
      redirect_to boat_path(@boat)
    end
  end

  private
  def load_boat
    @boat = Boat.find(params[:boat_id])
  end

  def load_instance
    @good = @boat.goods.find(params[:id])
  end

  def create_instance
    @good = @boat.goods.new
  end

  def good_params
    params.require(:good).permit(:name, :quantity) if params[:good]
  end

  def set_params
    @good.assign_attributes(good_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_boat.html.slim
tr
  td
    = link_to boat.name, boat_path(boat)
  td
    = boat.year
  td
    = image_tag boat.image.url, style: "max-width: 100px;"
  td
    = link_to t(".edit"), edit_boat_path(boat), remote: true, class: "btn btn-primary mar-right-5"
    = link_to t(".delete"), boat_path(boat), method: :delete, class: "btn btn-danger",
      data: {confirm: t("dictionary.question_destroy")}

app/views/boats/_modal_form.html.slim
.modal.fade#jmodal-boat-form
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4.modal-title= t(".title")
      .modal-body
        = form_for Boat.new, html: {id: "jboat-form"} do |f|
          table.table.table-striped
            tr
              th= Boat.h :name
              td= f.text_field :name, class: "form-control", id: "jboat-name", required: true
            tr
              th= Boat.h :year
              td= f.number_field :year, min: 0, class: "form-control", id: "jboat-year", required: true
            tr
              th= Boat.h :image
              td= f.file_field :image, class: "form-control", id: "jboat-image", required: true
          .txt-align-right
            = f.submit t(".submit"), class: "button btn btn-primary"

app/views/boats/edit.js.erb
$(".modal-title").text("<%= I18n.t("boats.modal_form.edit_title") %>");
$("#jboat-form").attr("action", "/boats/" + <%= @boat.id %>);
$("#jboat-name").val("<%= @boat.name %>");
$("#jboat-year").val("<%= @boat.year %>");
$("#jboat-form").append('<input type="hidden" name="_method" value="PUT">');
$("#jmodal-boat-form").modal("show");

app/views/boats/index.html.slim
.row
  .col-lg-12
    h1.page-header
      = t ".title"

.row style="padding-bottom: 10px;"
  .col-md-12
    .row
      .col-md-2
        = link_to t(".new"), "javascript:", class: "btn btn-block btn-primary", id: "jnew-boat"

.row
  .col-lg-12
    table.table.table-striped.table-bordered.table-hover
      thead
        tr
          th
            = Boat.h :name
          th
            = Boat.h :year
          th
            = Boat.h :image
          th
            = t ".option_label"
      tbody
        = render partial: "boat", collection: @boats
    = paginate @boats

= render "modal_form"

app/views/boats/show.html.slim
.row
  .col-lg-12
    h1.page-header= t(".title", name: @boat.name)
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        = t ".boat_heading"
      .panel-body
        .table-responsive
          table.table.table-striped
            tr
              th= Boat.h :name
              td= @boat.name
            tr
              th= Boat.h :year
              td= @boat.year
            tr
              th= Boat.h :image
              td= image_tag @boat.image.url, class: "size-img-medium"

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        div
          span.mar-right-5= t ".goods_heading"
          = link_to t(".add_goods_label"), new_boat_good_path(@boat), class: "btn btn-sm btn-primary"
      .panel-body
        .table-responsive
          table.table
            thead
              tr
                th
                  = Good.h :name
                th
                  = Good.h :quantity
                th
                  = t ".option_label"
            tbody
              = render partial: "goods/good", collection: @goods

app/views/goods/_form.html.slim
= form_for [@boat, @good] do |f|
  table.table.table-striped
    tr
      th= Good.h :name
      td= f.text_field :name, class: "form-control", required: true
    tr
      th= Good.h :quantity
      td= f.number_field :quantity, min: 0, class: "form-control", required: true
  .txt-align-right
    = link_to t(".cancle"), boat_path(@boat), class: "btn btn-default mar-right-5"
    = f.submit t(".submit"), class: "button btn btn-primary"

app/views/goods/_good.html.slim
tr
  td= good.name
  td= good.quantity
  td
    = link_to t(".edit"), edit_boat_good_path(@boat, good), class: "btn btn-primary mar-right-5"
    = link_to t(".delete"), boat_good_path(@boat, good), method: :delete, class: "btn btn-danger",
      data: {confirm: t("dictionary.question_destroy")}

app/views/goods/edit.html.slim
.row
  .col-lg-12
    h1.page-header= t(".title", name: @good.name)
= render "form"

app/views/goods/new.html.slim
.row
  .col-lg-12
    h1.page-header= t(".title")
= render "form"

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      = link_to "NovaTest", root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li.active
          = link_to "NovaTest", root_path
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Sign out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title NovaTest
    = stylesheet_link_tag :application, media: 'all'
    = javascript_include_tag :application
    = csrf_meta_tags
  body
    - if user_signed_in?
      #wrapper
        = render 'layouts/header'
    .container
      = render "shared/display_notice_message"
      = yield

app/views/shared/_display_notice_message.html.slim
- if flash[:success].present?
  .alert.alert-success.alert-dismissable
    button.close aria-hidden="true" data-dismiss="alert" type="button"  ×
    ul
      li= flash[:success]

- if flash[:errors].present?
  .alert.alert-danger.alert-dismissable
    button.close aria-hidden="true" data-dismiss="alert" type="button"  ×
    ul
      - flash[:errors].each do |msg|
        li= msg